name: laptop-marketplace
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/laptop-marketplace/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - api
      - client
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./client/.env

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./server/.env.dev
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: baotrung285
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    mem_limit: 128m

volumes:
  db-data:
