name: laptop-marketplace
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/laptop-marketplace/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    depends_on:
      - api

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   env_file:
  #     - ./client/.env
  #   ports:
  #     - 3000:3000

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env.dev
    ports:
      - 3001:3001
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: baotrung285
    mem_limit: 128m
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
