### Get all products
GET http://localhost:3001/api/products

### Get product with id
GET http://localhost:3001/api/products/12

### Create a product
POST http://localhost:3001/api/products
Content-Type: application/json

{
    "brand": 1,
    "category": 1,
    "name": "New Product",
    "price": 100,
    "description": "This is a new product",
    "stock_quantity": 100,
    "status": "old"
}

### Update a product
PUT http://localhost:3001/api/products/12
Content-Type: application/json

{
    "brand": 1,
    "category": 1,
    "name": "New Product"
    "price": 100,
    "description": "This is a new product",
    "stock_quantity": 100,
    "status": "old"
}

### Delete a product
DELETE http://localhost:3001/api/products/12

### Create new rating for a product
POST http://localhost:3001/api/products/1/ratings
Content-Type: application/json

{
    "ratingStar": 4,
    "comment": "Product is good"
}

# GET /api/products/:id/ratings - Get all ratings for a product


# ### Get product's specification
# GET http://localhost:3001/api/products/12/specifications

# ### Update product's specification
# PUT http://localhost:3001/api/products/12/specifications
# Content-Type: application/json

{
    "cpu":"string",
    "ram":"string",
    "storage":"string",
    "gpu":"string",
    "display":"string",
    "port":"string",
    "keyboard":"string",
    "lan":true,
    "wifi":true,
    "bluetooth":true,
    "webcam":true,
    "os":"string",
    "battery":10,
    "weight":10,
    "color":"string",
    "dimensions":"string"
}//can add only attributes that you want to update

# ### Get product's images
# GET http://localhost:3001/api/products/12/images

# ### Add product's specification
# POST http://localhost:3001/api/products/12/images
Content-Type: application/json

{
    "cpu":"string",
    "ram":"string",
    "storage":"string",
    "gpu":"string",
    "display":"string",
    "port":"string",
    "keyboard":"string",
    "lan":true,
    "wifi":true,
    "bluetooth":true,
    "webcam":true,
    "os":"string",
    "battery":10,
    "weight":10,
    "color":"string",
    "dimensions":"string"
}

# ### Delete a product's image
# DELETE http://localhost:3001/api/products/12/images/13