import { Product } from "@/types";

export const productListExample: Product[] = [
  {
    id: 1,
    name: "Laptop Dell XPS 13",
    price: 1500,
    description: "Laptop cao cấp với màn hình 13.4 inch, CPU Intel Core i7, RAM 16GB.",
    stockQuantity: 10,
    status: "new",
    seller: {
      id: 101,
      email: "seller1@example.com",
      phoneNumber: "0123456789",
      name: "Dell Official Store",
      avatar: "/avatar.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 1, name: "Dell" },
    category: { id: 1, type: "Laptop" },
    ratings: [
      {
        id: 1,
        ratingStar: 5,
        comment: "Sản phẩm rất tuyệt!",
        product: {} as Product, // Tránh lỗi vòng lặp
        buyer: {
          id: 202,
          email: "buyer1@example.com",
          phoneNumber: "0987654321",
          name: "Nguyễn Văn A",
          avatar: "/buyer-avatar.png",
          googleId: null,
          role: { roleName: "buyer" },
        },
      },
    ],
    images: [
      { id: 0, image: "/product.png" },
      { id: 1, image: "/product.png" },
    ],
  },
  {
    id: 2,
    name: "MacBook Pro 14",
    price: 2000,
    description: "MacBook Pro với chip M2, RAM 16GB, SSD 512GB.",
    stockQuantity: 5,
    status: "new",
    seller: {
      id: 102,
      email: "seller2@example.com",
      phoneNumber: "0321654987",
      name: "Apple Store",
      avatar: "/avatar2.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 2, name: "Apple" },
    category: { id: 1, type: "Laptop" },
    ratings: [],
    images: [{ id: 0, image: "/product.png" }],
  },
  {
    id: 3,
    name: "MacBook Product 3",
    price: 2000,
    description: "MacBook Pro với chip M2, RAM 16GB, SSD 512GB.",
    stockQuantity: 5,
    status: "new",
    seller: {
      id: 102,
      email: "seller2@example.com",
      phoneNumber: "0321654987",
      name: "Apple Store",
      avatar: "/avatar2.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 2, name: "Apple" },
    category: { id: 1, type: "Laptop" },
    ratings: [],
    images: [{ id: 0, image: "/product.png" }],
  },
  {
    id: 4,
    name: "MacBook P4",
    price: 2000,
    description: "MacBook Pro với chip M2, RAM 16GB, SSD 512GB.",
    stockQuantity: 5,
    status: "new",
    seller: {
      id: 102,
      email: "seller2@example.com",
      phoneNumber: "0321654987",
      name: "Apple Store",
      avatar: "/avatar2.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 2, name: "Apple" },
    category: { id: 1, type: "Laptop" },
    ratings: [],
    images: [{ id: 0, image: "/product.png" }],
  },
  {
    id: 5,
    name: "MacBook P5",
    price: 2000,
    description: "MacBook Pro với chip M2, RAM 16GB, SSD 512GB.",
    stockQuantity: 5,
    status: "new",
    seller: {
      id: 102,
      email: "seller2@example.com",
      phoneNumber: "0321654987",
      name: "Apple Store",
      avatar: "/avatar2.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 2, name: "Apple" },
    category: { id: 1, type: "Laptop" },
    ratings: [],
    images: [{ id: 0, image: "/product.png" }],
  },
  {
    id: 2,
    name: "MacBook P6",
    price: 2000,
    description: "MacBook Pro với chip M2, RAM 16GB, SSD 512GB.",
    stockQuantity: 5,
    status: "new",
    seller: {
      id: 102,
      email: "seller2@example.com",
      phoneNumber: "0321654987",
      name: "Apple Store",
      avatar: "/avatar2.png",
      googleId: null,
      role: { roleName: "seller" },
    },
    brand: { id: 2, name: "Apple" },
    category: { id: 1, type: "Laptop" },
    ratings: [],
    images: [{ id: 0, image: "/product.png" }],
  },
];
