### Sign in user
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "password"
}

### Sign up user
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "password",
    "phoneNumber": "0327734064",
    "name": "trungdz"
}

### Get all user (admin)
GET http://localhost:3000/api/accounts

### Get account detail (admin)
GET http://localhost:3000/api/accounts/12

### Get profile
GET http://localhost:3000/api/accounts/profile

### Update profile
PUT http://localhost:3000/api/accounts/profile